/**
 * Source-image optimizer. Run after dropping new generated images into
 * public/images:
 *
 *   npm run optimize:images   (or: bun scripts/optimize-images.ts)
 *
 * Downscales oversized JPEGs to the largest size any layout slot actually
 * renders (with 2x retina headroom) and re-encodes with mozjpeg. This
 * shrinks the repo and deploys; the runtime formats (WebP/AVIF) and
 * per-device srcsets are generated by next/image + Vercel's image
 * optimizer at request time, so sources stay JPEG on purpose: paths in
 * content files never change and Sebastian's drop-in workflow stays the
 * same.
 *
 * Idempotent in practice: files already at/below the size cap and byte
 * threshold are skipped, so re-running never re-compresses (and never
 * generation-loss-degrades) an already-optimized image.
 */

import { readdir, stat, rename, unlink } from "node:fs/promises";
import { join, extname } from "node:path";
import sharp from "sharp";

const ROOT = join(import.meta.dirname, "..", "public", "images");

/** Max width per path prefix; everything else falls back to DEFAULT_MAX */
const WIDTH_CAPS: [prefix: string, maxWidth: number][] = [
  // Full-bleed 100vw background: keep near-native width
  ["cta-treetops", 2560],
];
const DEFAULT_MAX = 1600;
const JPEG_QUALITY = 80;
// Files this small are considered already optimized and are skipped
const SKIP_UNDER_BYTES = 400 * 1024;

async function* walk(dir: string): AsyncGenerator<string> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

const fmt = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)}MB`;

let totalBefore = 0;
let totalAfter = 0;
let touched = 0;

for await (const file of walk(ROOT)) {
  if (![".jpg", ".jpeg"].includes(extname(file).toLowerCase())) continue;

  const before = (await stat(file)).size;
  const rel = file.slice(ROOT.length + 1);
  if (before < SKIP_UNDER_BYTES) {
    console.log(`skip  ${rel} (${fmt(before)}, already small)`);
    continue;
  }

  const cap =
    WIDTH_CAPS.find(([prefix]) => rel.includes(prefix))?.[1] ?? DEFAULT_MAX;
  const tmp = `${file}.tmp`;
  await sharp(file)
    .resize({ width: cap, withoutEnlargement: true })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
    .toFile(tmp);

  const after = (await stat(tmp)).size;
  if (after >= before) {
    // Recompression didn't help; keep the original
    await unlink(tmp);
    console.log(`keep  ${rel} (${fmt(before)}, recompression not smaller)`);
    continue;
  }

  await rename(tmp, file);
  totalBefore += before;
  totalAfter += after;
  touched += 1;
  console.log(`done  ${rel}  ${fmt(before)} -> ${fmt(after)}`);
}

console.log(
  touched === 0
    ? "\nNothing to optimize."
    : `\nOptimized ${touched} images: ${fmt(totalBefore)} -> ${fmt(totalAfter)} (saved ${fmt(totalBefore - totalAfter)})`
);
